### ISSUE TITLE
Program crash problem

### ISSUE THREAD

**Issue by Hu-Said** [sipsorcery-org/SIPSorceryMedia.Windows#19]
**During the process of sending the video, decoding failed and the program crashed. The following is the error stack information:**

System.ApplicationException: VP8 encode attempt failed, Unspecified internal error.
   at SIPSorceryMedia.Encoders.Codecs.Vp8Codec.Encode(Byte[] frame, VpxImgFmt inputPixelFormat, Boolean forceKeyFrame)
   at SIPSorceryMedia.Encoders.VpxVideoEncoder.EncodeVideo(Int32 width, Int32 height, Byte[] sample, VideoPixelFormatsEnum pixelFormat, VideoCodecsEnum codec)
   at SIPSorceryMedia.Windows.WindowsVideoEndPoint.FrameArrivedHandler(MediaFrameReader sender, MediaFrameArrivedEventArgs e)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()

**Comment by Hu-Said** [comment]
![image](https://github.com/sipsorcery-org/SIPSorceryMedia.Windows/assets/63393002/a421f2a9-32c8-47c5-b479-bca90177229b)
Adding exception handling to this method can solve the problem
